upstream web {
  ip_hash;
  server web:8000;
}

# redirect to https
server {
  listen 80 default_server;
  listen [::]:80 default_server;
  server_name _;
  return 301 https://$host$request_uri;
}

# portal
server {
  listen 8000;
  server_name localhost;

  location = /favicon.ico { access_log off; log_not_found off; }
  location /static/ {
    root /src;
  }

  location / {
    proxy_set_header X-Forwarded-Proto https;
    proxy_pass http://web;
  }
}