# Generated by Django 4.0.4 on 2022-04-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_t',
            field=models.CharField(max_length=15),
        ),
    ]
