# Generated by Django 4.0.2 on 2022-02-18 03:36

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReflectionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeling', models.IntegerField()),
                ('adjective', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Happy'), (2, 'Confident'), (3, 'Excited')], max_length=5)),
                ('reason', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Family'), (2, 'Friends'), (3, 'Work'), (4, 'School')], max_length=7)),
                ('rose', models.CharField(max_length=500)),
                ('bud', models.CharField(max_length=500)),
                ('thorn', models.CharField(max_length=500)),
            ],
        ),
    ]
