# Generated by Django 4.0.2 on 2022-03-09 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjectiveChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeling', models.IntegerField()),
                ('order', models.IntegerField()),
                ('adjective', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ReflectionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('feeling', models.IntegerField()),
                ('adjective', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Hurt'), (2, 'Depressed'), (3, 'Angry'), (4, 'Stressed'), (5, 'Anxious'), (6, 'Lonely'), (7, 'Neglected'), (8, 'Guilty'), (9, 'Panicked '), (10, 'Frightened'), (11, 'Helpless'), (1, 'Uncomfortable'), (2, 'Tired'), (3, 'Nervous'), (4, 'Annoyed'), (5, 'Worried'), (6, 'Irritated'), (7, 'Upset'), (8, 'Off-balanced'), (9, 'Frustrated'), (10, 'Jealous'), (11, 'Stressed'), (1, 'Content'), (2, 'Comfortable'), (3, 'Relaxed'), (4, 'Relieved'), (5, 'Bored'), (6, 'Confused'), (7, 'Distant'), (8, 'Calm'), (9, 'Tired'), (10, 'Distracted'), (11, 'Busy'), (1, 'Carefree'), (2, 'Grateful'), (3, 'Happy'), (4, 'Satisfied'), (5, 'Eager'), (6, 'Helpful'), (7, 'Hopeful'), (8, 'Proud'), (9, 'Triumphant'), (10, 'Pleased'), (11, 'Fulfilled'), (1, 'Grateful'), (2, 'Excited'), (3, 'Proud'), (4, 'Hopeful'), (5, 'Motivated'), (6, 'Joyful'), (7, 'Loved'), (8, 'Confident'), (9, 'Elated'), (10, 'Inspired'), (11, 'Brave')], max_length=119)),
                ('reason', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Family'), (2, 'Friends'), (3, 'Relationships'), (4, 'School'), (5, 'Health'), (6, 'News'), (7, 'Expectations'), (8, 'Hobbies'), (9, 'Exercise'), (10, 'Work')], max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
