# Generated by Django 4.0.2 on 2022-03-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=32)),
                ('happysad', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='reflectionentry',
            options={'ordering': ['-date']},
        ),
    ]
