# Generated by Django 4.0.2 on 2022-02-18 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reflection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflectionentry',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reflectionentry',
            name='bud',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='reflectionentry',
            name='rose',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='reflectionentry',
            name='thorn',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
