# Generated by Django 4.0.2 on 2022-02-19 03:03

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reflection', '0002_reflectionentry_user_alter_reflectionentry_bud_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjectiveChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeling', models.IntegerField()),
                ('order', models.IntegerField()),
                ('adjective', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='reflectionentry',
            name='adjective',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Sad'), (2, 'Annoyed'), (3, 'Stressed'), (1, 'Sad'), (2, 'Annoyed'), (3, 'Stressed'), (1, 'Neutral'), (2, 'Bored'), (3, 'Content'), (1, 'Happy'), (2, 'Confident'), (3, 'Excited'), (1, 'Happy'), (2, 'Confident'), (3, 'Excited')], max_length=29),
        ),
    ]
