# Generated by Django 4.0.2 on 2022-03-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflection', '0002_quoteresponse_alter_reflectionentry_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quote', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
