# Generated by Django 4.0.2 on 2022-02-22 03:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reflection', '0003_adjectivechoice_alter_reflectionentry_adjective'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflectionentry',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
