# Generated by Django 4.0.2 on 2022-04-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('link', models.URLField(max_length=300)),
                ('resource_t', models.CharField(max_length=10)),
            ],
        ),
    ]
