# Generated by Django 4.0.2 on 2022-04-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflectionentry',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
