# Generated by Django 4.0.4 on 2022-04-20 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflection', '0002_reflectionentry_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflectionentry',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
